version: "3.9"
services:
  ioc-seismometer:
    container_name: ioc-seismometer
    image: public.ecr.aws/debian/debian:10-slim
    stdin_open: true
    tty: true
    network_mode: "host"
    env_file: 
      - ./.env
    volumes:
      - ${DAS_PATH}:${DAS_PATH}
    build: 
      context: "."
      args:
        DAS_PATH: ${DAS_PATH}
        PV_PREFIX: ${PV_PREFIX}