version: "3.6"
services:
  ioc-seismometer:
    stdin_open: true
    tty: true
    image: public.ecr.aws/debian/debian:10-slim
    build: 
      context: "."
    volumes:
      - /home/reftek/bin:/home/reftek/bin